version: "3"
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=cubby_server
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cubby_server
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata

  account:
    build: 
      context: ./account
    restart: always
    depends_on:
      - db
    expose: 
      - 3001

  nginx:
    image: nginx:1.21-alpine
    restart: always
    depends_on:
      - account
    ports:
      - 3000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx

volumes:
  db:
